title: TechLab Entra Suite for Frontier Transformation
description: This lab will guide you through the process of creating a Cloud User Account (CUA) with Windows 365 for Agents. You will learn how to set up and configure the necessary components to enable secure access and management of your organization's resources.

aux_links:
  "TechLab: Entra Suite for Frontier Transformation": 
    - "https://github.com/microsoft/TWL300-Entra-Suite-for-Frontier-Transformation/"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note 
    color: purple
  warning:
    title: Warning
    color: red
